name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  

      - name: Prepare Docs Directory
        run: |
          # Copiar los archivos generados a la raíz de gh-pages
          cp -r Payment/_site/* Payment/
          cp -r ATM/_site/* ATM/
          cp -r Comportamiento/_site/* Comportamiento/

      - name: Copy main index.html to gh-pages
        run: cp index.html ./index.html

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PACKAGES_TOKEN }}
          publish_dir: .  
