name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar .NET 9.0 SDK
      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3. Instalar DocFX
      - name: Install DocFX
        run: dotnet tool install -g docfx

      # 4. Construir documentación
      - name: Build documentation
        run: |
          docfx Payment/docfx.json
          docfx ATM/docfx.json
          docfx Comportamiento/docfx.json

      # 5. Guardar el index.html de la rama main
      - name: Save index.html from main branch
        run: cp index.html /tmp/index.html

      # 6. Cambiar a la rama gh-pages
      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin gh-pages
          git checkout gh-pages

      # 7. Limpiar contenido anterior y copiar nueva documentación
      - name: Copy built docs and index.html
        run: |
          rm -rf Payment ATM Comportamiento index.html

          mkdir -p Payment ATM Comportamiento

          cp -r Payment/_site/* Payment/
          cp -r ATM/_site/* ATM/
          cp -r Comportamiento/_site/* Comportamiento/

          cp /tmp/index.html .

      # 8. Commit y push
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Actualizar documentación desde rama main" || echo "Sin cambios para commitear"
          git push origin gh-pages
