name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Guardar el index.html de la rama main
      - name: Save index.html from main branch
        run: cp index.html /tmp/index.html

      # 3. Limpiar directorio de trabajo antes de cambiar de rama
      - name: Clean working directory before switching branches
        run: |
          git reset --hard
          git clean -fdX

      # 4. Cambiar a la rama gh-pages
      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git pull origin gh-pages || echo "La rama gh-pages no tiene cambios aún."

      # 5. Limpiar contenido anterior y copiar nueva documentación
      - name: Copy built docs and index.html
        run: |
          # Eliminar los directorios anteriores solo si existen
          rm -rf Payment ATM Comportamiento index.html || echo "No se encontraron los directorios o archivos para borrar"

          # Crear los directorios de destino si no existen
          mkdir -p Payment ATM Comportamiento

          # Copiar los archivos desde la rama main (si existen)
          cp -r Payment/* Payment/ || echo "No hay archivos en Payment"
          cp -r ATM/* ATM/ || echo "No hay archivos en ATM"
          cp -r Comportamiento/* Comportamiento/ || echo "No hay archivos en Comportamiento"

          # Copiar el index.html
          cp /tmp/index.html . || echo "No se encontró index.html"
